name: build
on: [pull_request, push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.6]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install xmlsec1 (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt -y install xmlsec1

      - name: Install xmlsec (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libxml2 libxmlsec1 pkg-config
          pip install xmlsec

      - name: Create test certs
        run: |
          cd test/pki
          ./create-cert.sh

      - name: Install dependencies
        run: poetry install

      - name: Generate metadata
        run: |
          cd test/metadata
          poetry run python generate_metadata.py

      - name: Run pytest
        run: poetry run pytest

      - name: Run flake8
        run: poetry run flake8

      - name: Run pytest with coverage
        run: poetry run pytest --cov --cov-report term --cov-report xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
